### ISSUE TITLE
Хуки

### ISSUE THREAD

**Issue by WinterSilence** [Alexkurd/wa-apps#7]
А почему нет поддержки хуков вида `wa('contacts')->event('mailer.recipients.form', $params)`, `wa()->event(array('contacts', 'contacts_collection'), $params))`?

**Comment by Alexkurd** [comment]
Можете добавить, еще не все хуки есть.

**Comment by WinterSilence** [comment]
@Alexkurd я думал ты автоматом распарсил

**Comment by Alexkurd** [comment]
Авто формирует общий список, некоторые события вызываются нестанадртно поэтом их сразу и нет.
Список есть в каждом файле например в комментариях.
https://github.com/Alexkurd/apps/blob/master/lib/config/data/contacts.php

**Comment by WinterSilence** [comment]
@Alexkurd кинь ссылку на то место где парсится код, напишу регулярки

**Comment by Alexkurd** [comment]
egrep -r -i -E --include \*.php --exclude-dir={'apps','wa-data'} "wa(\)|.+)>event\(.+\)" > all_events.txt

**Comment by WinterSilence** [comment]
@Alexkurd а wa-data зачем?

**Comment by Alexkurd** [comment]
Исключить же. Нам не нужна папка исходного приложения и не проверять содержимое wa-data.

**Comment by WinterSilence** [comment]
@Alexkurd туплю) видел еще какие-то варианты кроме описанных мной?

**Comment by Alexkurd** [comment]
wa()->event(array_shift($events), $data)
frontend_action_'.$action, $params, $fields);
wa()->event(array($this->application, 'routing'), $route);
wa($app_id)->event(array($app_id, 'personal.settings'), $event_params);
wa()->event(array($this->app_id, 'sitemap'), $route);
wa()->event(array($this->application, 'routing'), $route);
'order_action_form.'.$action_id, $data);
'order_action.'.$this->getId(), $data);

**Comment by WinterSilence** [comment]
@Alexkurd ` 'order_action.'.$this->getId(), $data);` а можешь показать всю строку?

**Comment by Alexkurd** [comment]
wa('shop')->event('order_action.'.$this->getId(), $data);
https://github.com/webasyst/shop-script/blob/4f20f3fb49c54f366a94e11d3c1bbc515e7efc3f/lib/workflow/shopWorkflowAction.class.php#L260

**Comment by WinterSilence** [comment]
`(wa|waSystem::getInstance)\(('\w*')*\)->event\((.*)?(,(.*))*\)`
